### ISSUE TITLE
App::Rak:ver<0.2.7> vs App::Rak:ver<0.2.9>

### ISSUE THREAD

**Issue by frithnanth** [lizmat/App-Rak-Complete#1]
Hello,
while the `META6.json` asks for an `App::Rak:ver<0.2.9>:auth<zef:lizmat>`, the `Complete.rakumod` file tries to `use App::Rak:ver<0.2.7>:auth<zef:lizmat>;` .

**Comment by lizmat** [comment]
Thanks for the headsup.  Fixed with version 0.0.6
